---
# tasks file for geekbr

- hosts: srvweb1
  vars:
    var_zabbix_server: '192.168.1.116'
    web_root: /hosts
    web_group: hosting
    web_user: geek
    mysql_root_password: scaleway_rootpass
    user_password: $6$NQ48t/llAxQcfZzO$Rqo/ymaNp./qrZ6a3rmZso1n9KEYdoVf3z4EAV63tZjSIb5t9pNanYXMDAc3EKXXGSIFlpjLfg1tP./2LwWLu/
    domains:
     - geekblog.xyz

  tasks:
    
    - name: Include a play after another play
      include: basic_installation.yml



    - name: Include a play after another play
      include: install_php.yml

    - name: Include a play after another play
      include: setup_nginx_vhosts.yml

    - name: Include a play after another play
      include: install_mariadb.yml

    - name: Include a play after another play
      include: create_dbuser_wordpress.yml


  handlers:

    - name: restart zabbix-agent
      systemd:
          state: restarted
          daemon_reload: yes
          name: zabbix-agent
      tags: zabbix

    - name: restart nginx
      systemd:
          state: restarted
          daemon_reload: yes
          name: nginx

    - name: restart php-fpm
      systemd:
          state: restarted
          daemon_reload: yes
          name: php-fpm