      - name: "Ensure mariadb packages are installed"
        yum: 
          name: '{{ packages }}' 
          state: present
        vars:
          packages:
              - mariadb
              - mariadb-server
              - python2-PyMySQL

      - name: "Ensure mariadb is running and configured to start at boot"
        service: 
          name: mariadb
          state: started 
          enabled: yes



  # set mysql root password

      - name: Template a file to /tmp/update_mysql_root_pass.sql
        template:
            src: update_mysql_root_pass.j2
            dest: /tmp/update_mysql_root_pass.sql
            owner: root
            group:  root
            mode: '0600'

      - name: Execute /tmp/update_mysql_root_pass.sql
        shell: mysql < /tmp/update_mysql_root_pass.sql

  # delete set mysql root password sql file

      - name: Remove /tmp/update_mysql_root_pass.sql
        file:
          path: /tmp/update_mysql_root_pass.sql
          state: absent

