# Install PHP 7.2 as php-fpm
      - name: Install PHP
        yum: name={{ packages }} state=present enablerepo=remi-php72
        vars:
            packages:
            - php
            - php-fpm 
            - php-cli 
            - php-mysql 
            - php-gd 
            - php-ldap 
            - php-odbc 
            - php-pdo 
            - php-pecl-memcache 
            - php-opcache 
            - php-pear 
            - php-xml 
            - php-xmlrpc 
            - php-mbstring 
            - php-snmp 
            - php-soap 
            - php-zip

      - name: Make sure php-fpm service is running
        systemd:
            state: started
            enabled: true
            name: php-fpm

      - name: Make sure nginx service is running
        systemd:
            state: started
            enabled: true
            name: nginx
    

      - name: copy vhostnginx.conf file from local host to remote host (absolute path)
        copy:
          src:  files/nginx_wp.conf
          dest: /etc/nginx/nginx.conf
        notify:
          - restart nginx
          - restart php-fpm

      - name: copy info.php file from local host to remote host (absolute path)
        copy:
          src:  files/info.php
          dest: /var/www/html/info.php

      - name: copy index.html file from local host to remote host (absolute path)
        copy:
          src:  files/index.html
          dest: /var/www/html/index.html





      - name: copy file from local host to remote host (absolute path)
        copy:
          src:  files/www.conf
          dest: /etc/php-fpm.d/www.conf
        notify:
          - restart nginx
          - restart php-fpm







  # handlers:

  #   - name: restart nginx
  #     systemd:
  #         state: restarted
  #         daemon_reload: yes
  #         name: nginx

  #   - name: restart php-fpm
  #     systemd:
  #         state: restarted
  #         daemon_reload: yes
  #         name: php-fpm
